// <auto-generated>
// Rewired Constants
// This list was generated on 3/28/2018 1:52:54 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // Move
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Move", friendlyName = "Vertical Move")]
        public const int Vertical_Move = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Move", friendlyName = "Horizontal Move")]
        public const int Horizontal_Move = 1;
        // Turn
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Turn", friendlyName = "Vertical Turn")]
        public const int Vertical_Turn = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Turn", friendlyName = "Horizontal Turn")]
        public const int Horizontal_Turn = 4;
        // Action
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Action", friendlyName = "Bump")]
        public const int Bump = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Action", friendlyName = "Launch")]
        public const int Launch = 5;
        // System
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "System", friendlyName = "Pause")]
        public const int Pause = 6;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 1;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2")]
        public const int Player2 = 2;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player3")]
        public const int Player3 = 3;
    }
    public static partial class CustomController {
    }
}
